import { ClerkProvider, UserButton } from "@clerk/nextjs";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClerkProvider>
          <header className="flex justify-between">
            <h1 className="text-black ">LOGO</h1>
            <UserButton showName />
          </header>
        </ClerkProvider>

        {children}
      </body>
    </html>
  );
}
